### ISSUE TITLE
Redundant release log

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#170]
When publishing new packages without using changeset CLI, release logs of old versions weirdly exist in the new release log.

<img width="424" alt="image" src="https://user-images.githubusercontent.com/7312949/199766954-801d3eab-ff87-4310-a896-d3e602cc2182.png">

@lawvs any ideas?

**Comment by lawvs** [comment]
Maybe we can add an option to prevent changesets create GitHub releases.

```yml
  createGithubReleases:
    description: "A boolean value to indicate whether to create Github releases after `publish` or not"
    required: false
    default: true
```
