### ISSUE TITLE
Update new color system​ to blocksuite

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#2009]
Related to https://github.com/toeverything/AFFiNE/issues/1796

### Light

```css
:root {
  --affine-brand-color: rgb(84, 56, 255);
  --affine-tertiary-color: rgb(243, 240, 255);
  --affine-primary-color: rgb(84, 56, 255);
  --affine-secondary-color: rgb(125, 145, 255);
  --affine-background-success-color: rgb(255, 255, 255);
  --affine-background-error-color: rgba(255, 255, 255, 0.2);
  --affine-background-processing-color: rgb(255, 255, 255);
  --affine-background-warning-color: rgb(255, 255, 255);
  --affine-background-primary-color: rgb(255, 255, 255);
  --affine-background-overlay-panel-color: rgb(251, 251, 252);
  --affine-background-secondary-color: rgb(251, 250, 252);
  --affine-background-tertiary-color: rgb(233, 233, 236);
  --affine-background-code-block: rgb(250, 251, 253);
  --affine-background-modal-color: rgba(0, 0, 0, 0.6);
  --affine-text-primary-color: rgb(66, 65, 73);
  --affine-text-secondary-color: rgb(142, 141, 145);
  --affine-text-disable-color: rgb(169, 169, 173);
  --affine-text-emphasis-color: rgb(84, 56, 255);
  --affine-hover-color: rgba(0, 0, 0, 0.04);
  --affine-link-color: rgb(125, 145, 255);
  --affine-quote-color: rgb(100, 95, 130);
  --affine-icon-color: rgb(119, 117, 125);
  --affine-icon-secondary: rgba(119, 117, 125, 0.6);
  --affine-border-color: rgb(227, 226, 228);
  --affine-divider-color: rgb(227, 226, 228);
  --affine-placeholder-color: rgb(192, 191, 193);
  --affine-edgeless-grid-color: rgb(230, 230, 230);
  --affine-success-color: rgb(16, 203, 134);
  --affine-warning-color: rgb(255, 99, 31);
  --affine-error-color: rgb(235, 67, 53);
  --affine-processing-color: rgb(39, 118, 255);
  --affine-black-10: rgba(0, 0, 0, 0.1);
  --affine-black-30: rgba(0, 0, 0, 0.3);
  --affine-black-50: rgba(0, 0, 0, 0.5);
  --affine-black-60: rgba(0, 0, 0, 0.6);
  --affine-black-80: rgba(0, 0, 0, 0.8);
  --affine-black-90: rgba(0, 0, 0, 0.9);
  --affine-black: rgb(0, 0, 0);
  --affine-white-10: rgba(255, 255, 255, 0.1);
  --affine-white-30: rgba(255, 255, 255, 0.3);
  --affine-white-50: rgba(255, 255, 255, 0.5);
  --affine-white-60: rgba(255, 255, 255, 0.6);
  --affine-white-80: rgba(255, 255, 255, 0.8);
  --affine-white-90: rgba(255, 255, 255, 0.9);
  --affine-white: rgb(255, 255, 255);
  --affine-tag-white: rgb(245, 245, 245);
  --affine-tag-gray: rgb(227, 226, 224);
  --affine-tag-red: rgb(255, 225, 225);
  --affine-tag-orange: rgb(255, 234, 202);
  --affine-tag-yellow: rgb(255, 244, 216);
  --affine-tag-green: rgb(223, 244, 232);
  --affine-tag-teal: rgb(223, 244, 243);
  --affine-tag-blue: rgb(225, 239, 255);
  --affine-tag-purple: rgb(243, 240, 255);
  --affine-tag-pink: rgb(252, 232, 255);
  --affine-palette-yellow: rgb(255, 232, 56);
  --affine-palette-orange: rgb(255, 175, 56);
  --affine-palette-tangerine: rgb(255, 99, 31);
  --affine-palette-red: rgb(252, 63, 85);
  --affine-palette-magenta: rgb(255, 56, 179);
  --affine-palette-purple: rgb(182, 56, 255);
  --affine-palette-navy: rgb(59, 37, 204);
  --affine-palette-blue: rgb(79, 144, 255);
  --affine-palette-green: rgb(16, 203, 134);
  --affine-palette-grey: rgb(153, 153, 153);
  --affine-palette-white: rgb(255, 255, 255);
  --affine-palette-black: rgb(0, 0, 0);
}
```

### Dark

```css
:root {
  --affine-brand-color: rgb(84, 56, 255);
  --affine-primary-color: rgb(118, 95, 254);
  --affine-secondary-color: rgb(144, 150, 245);
  --affine-tertiary-color: rgb(30, 30, 30);
  --affine-hover-color: rgba(255, 255, 255, 0.1);
  --affine-icon-color: rgb(168, 168, 160);
  --affine-border-color: rgb(57, 57, 57);
  --affine-divider-color: rgb(114, 114, 114);
  --affine-placeholder-color: rgb(62, 62, 63);
  --affine-quote-color: rgb(147, 144, 163);
  --affine-link-color: rgb(185, 191, 227);
  --affine-edgeless-grid-color: rgb(49, 49, 49);
  --affine-success-color: rgb(77, 213, 181);
  --affine-warning-color: rgb(255, 123, 77);
  --affine-error-color: rgb(212, 140, 130);
  --affine-processing-color: rgb(195, 215, 255);
  --affine-text-emphasis-color: rgb(208, 205, 220);
  --affine-text-primary-color: rgb(234, 234, 234);
  --affine-text-secondary-color: rgb(156, 156, 160);
  --affine-text-disable-color: rgb(119, 117, 125);
  --affine-black-10: rgba(255, 255, 255, 0.1);
  --affine-black-30: rgba(255, 255, 255, 0.3);
  --affine-black-50: rgba(255, 255, 255, 0.5);
  --affine-black-60: rgba(255, 255, 255, 0.6);
  --affine-black-80: rgba(255, 255, 255, 0.8);
  --affine-black-90: rgba(255, 255, 255, 0.9);
  --affine-black: rgb(255, 255, 255);
  --affine-white-10: rgba(0, 0, 0, 0.1);
  --affine-white-30: rgba(0, 0, 0, 0.3);
  --affine-white-50: rgba(0, 0, 0, 0.5);
  --affine-white-60: rgba(0, 0, 0, 0.6);
  --affine-white-80: rgba(0, 0, 0, 0.8);
  --affine-white-90: rgba(0, 0, 0, 0.9);
  --affine-white: rgb(0, 0, 0);
  --affine-background-code-block: rgb(41, 44, 51);
  --affine-background-tertiary-color: rgb(30, 30, 30);
  --affine-background-processing-color: rgb(255, 255, 255);
  --affine-background-error-color: rgb(255, 255, 255);
  --affine-background-warning-color: rgb(255, 255, 255);
  --affine-background-success-color: rgb(255, 255, 255);
  --affine-background-primary-color: rgb(20, 20, 20);
  --affine-background-hover-color: rgb(47, 47, 47);
  --affine-background-secondary-color: rgb(32, 32, 32);
  --affine-background-modal-color: rgba(0, 0, 0, 0.8);
  --affine-background-overlay-panel-color: rgb(30, 30, 30);
  --affine-tag-blue: rgb(10, 84, 170);
  --affine-tag-green: rgb(55, 135, 79);
  --affine-tag-teal: rgb(33, 145, 138);
  --affine-tag-white: rgb(84, 84, 84);
  --affine-tag-purple: rgb(59, 38, 141);
  --affine-tag-red: rgb(139, 63, 63);
  --affine-tag-pink: rgb(194, 132, 132);
  --affine-tag-yellow: rgb(187, 165, 61);
  --affine-tag-orange: rgb(231, 161, 58);
  --affine-tag-gray: rgb(41, 41, 41);
  --affine-palette-yellow: rgb(255, 232, 56);
  --affine-palette-orange: rgb(255, 175, 56);
  --affine-palette-tangerine: rgb(255, 99, 31);
  --affine-palette-red: rgb(252, 63, 85);
  --affine-palette-magenta: rgb(255, 56, 179);
  --affine-palette-purple: rgb(182, 56, 255);
  --affine-palette-navy: rgb(59, 37, 204);
  --affine-palette-blue: rgb(79, 144, 255);
  --affine-palette-green: rgb(16, 203, 134);
  --affine-palette-grey: rgb(153, 153, 153);
  --affine-palette-white: rgb(255, 255, 255);
  --affine-palette-black: rgb(0, 0, 0);
}
```
